# Service to expose the web app on port 3022
apiVersion: v1
kind: Service
metadata:
  name: mladminbot-service
  labels:
    app: mladminbot
spec:
  type: LoadBalancer   # Will act like NodePort in Docker Desktop
  selector:
    app: mladminbot
  ports:
    - port: 3022              # Port users connect to (can be any number)
      targetPort: 3022      # App's internal port inside the container
      nodePort: 30003
---
# Deployment for your app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mladminbot-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: mladminbot
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mladminbot
    spec:
      containers:
        - name: mladminbot-container
          image: mladminbot:latest    # Replace with your custom image
          imagePullPolicy: Always
          ports:
            - containerPort: 3022     # Matches the internal app port